# Generated by Django 5.1.2 on 2024-11-05 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('default_moderation', models.CharField(choices=[('deleted', 'Disallow Comments'), ('published', 'Approve Comments')], default='published', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('oauth_credentials', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prompt', models.TextField(blank=True)),
                ('positive_examples', models.TextField(blank=True, help_text='List of positive examples (optional)')),
                ('negative_examples', models.TextField(blank=True, help_text='List of negative examples (optional)')),
                ('action', models.CharField(choices=[('delete', 'Delete Comments'), ('publish', 'Publish Comments'), ('nothing', 'Do Nothing'), ('reply', 'Reply to Comments')], default='nothing', max_length=10)),
                ('reply_message', models.TextField(blank=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='promptfilter.channel')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='promptfilter.user'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_link', models.URLField(unique=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('posted_at', models.DateTimeField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='promptfilter.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('content', models.TextField()),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('posted_at', models.DateTimeField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('deleted', 'Deleted'), ('published', 'Published')], default='published', max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='promptfilter.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='promptfilter.user')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='promptfilter.video')),
            ],
        ),
        migrations.CreateModel(
            name='FilterPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.BooleanField(blank=True, null=True)),
                ('groundtruth', models.BooleanField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, help_text="Optional explanation for why the comment matched/don't match the filter", null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='promptfilter.comment')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='promptfilter.promptfilter')),
            ],
            options={
                'unique_together': {('filter', 'comment')},
            },
        ),
    ]
