# Generated by Django 5.1.2 on 2025-06-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptfilter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='default_moderation',
            field=models.CharField(choices=[('deleted', 'Disallow Comments'), ('published', 'Approve Comments'), ('reviewing', 'Hold Comments for Review')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('deleted', 'Deleted'), ('published', 'Published'), ('reviewing', 'Under Review')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='promptfilter',
            name='action',
            field=models.CharField(choices=[('deleted', 'Delete Comments'), ('published', 'Publish Comments'), ('reviewing', 'Hold Comments for Review'), ('nothing', 'Do Nothing')], default='nothing', max_length=10),
        ),
    ]
