# Generated by Django 5.1.2 on 2024-10-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptfilter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterprediction',
            name='created_at',
        ),
        migrations.AddField(
            model_name='promptfilter',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
