# Generated by Django 5.1.2 on 2025-01-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptfilter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promptfilter',
            name='examples',
        ),
        migrations.RemoveField(
            model_name='promptfilter',
            name='few_shot_examples',
        ),
        migrations.AddField(
            model_name='promptfilter',
            name='few_shot_examples',
            field=models.ManyToManyField(blank=True, related_name='filters', to='promptfilter.example'),
        ),
    ]
