# Generated by Django 5.1.2 on 2024-11-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptfilter', '0002_comment_total_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
