# Generated by Django 5.1.2 on 2024-10-30 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promptfilter', '0002_remove_filterprediction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filterprediction',
            unique_together={('filter', 'comment')},
        ),
    ]
