# Generated by Django 5.1.2 on 2024-11-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptfilter', '0003_user_last_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='second_last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
