# Generated by Django 5.1.2 on 2025-06-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptfilter', '0003_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptfilter',
            name='old_filter',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
