# Generated by Django 5.1.2 on 2024-11-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptfilter', '0003_alter_filterprediction_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
