# Generated by Django 5.1.2 on 2025-08-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptfilter', '0004_promptfilter_old_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.URLField(),
        ),
    ]
