# Generated by Django 5.1.2 on 2024-11-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptfilter', '0004_user_oauth_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptfilter',
            name='reply_message',
            field=models.TextField(blank=True),
        ),
    ]
