# Generated by Django 5.1.2 on 2025-08-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptfilter', '0007_filterprediction_experiment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptfilter',
            name='approach',
            field=models.CharField(blank=True, help_text='The approach used to create this filter. e.g., circle, square', max_length=50, null=True),
        ),
    ]
