# Generated by Django 5.1.2 on 2025-08-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptfilter', '0008_promptfilter_approach'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptfilter',
            name='calibrated',
            field=models.BooleanField(default=False, help_text='Whether this filter has been calibrated using the experiment calibration method.'),
        ),
    ]
