# Generated by Django 5.1.2 on 2025-08-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptfilter', '0009_promptfilter_calibrated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptfilter',
            name='calibrated',
            field=models.BooleanField(blank=True, help_text='Whether this filter has been calibrated using the experiment calibration method.', null=True),
        ),
    ]
